# Generated by Django 5.2.7 on 2025-11-09 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darpan_id_submitted', models.CharField(blank=True, max_length=50, null=True)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='ngo.ngoprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
